### ISSUE TITLE
Issue with static/connected route redistribution into OpenBGP

### ISSUE THREAD

**Issue by janakktrivedi** [openbgpd-portable/openbgpd-portable#39]
Hi,
I am running FreeBSD 13.0 with OpenBGPD software 5.2.20121209_4.
I am facing issue with static/connected route redistribution into BGP.
Here is the scenario:
FreeBSD firewall cluster is learning route from BGP peers from global routing table where route is learning from other site.
I am adding same route locally in Firewalls to advertise it locally, but BGP is not installing this static route in route table, although static routes should be prefered over BGP due to low AD value. bgpctl reload did not help too. But as soon as I restart the BGPD process(server openbgpd restart), static route works as expected.
In general, I want to announce same network/IP from multiple location to load balance the traffic towards nearest location.
Here is some of the statistics from the route table:

bgpctl show rib detail x.x.x.x

BGP routing table entry for x.x.x.x/32
    65003 65220
    Nexthop x.x.x.x (via y.y.y.y) from xxxx (y.y.y.y)
    Origin incomplete, metric 100, localpref 100, weight 0, internal, valid, best
    Last update: 00:48:59 ago
    Originator Id: y.y.y.y.y
    Cluster ID List: y.y.y.y

netstat -rn | grep x.x.x.x
x.x.x.x      y.y.y.y     UGH1    vlan133     <<<<<<<<<<<<<<< This route is being learn from BGP upstream peers
x.x.x.x      z.z.z.z         UGHS    vlan133  <<<<<<<<<<<<<<< This route is static added locally in firewalls.

I would like to know if this is expected behaviour in FreeBSD openbgpd or is there any bug in it. Btw, the same routing behavour works fine in OpenBSD openbgpd since almost 10 years without any issues.

**Comment by cjeker** [comment]
First of all the FreeBSD openbgpd 5.2 port is out of support for a long
long long long long long long time. A lot has changed since then.

FreeBSD 13 has a couple of annoying bugs when it comes to the route
socket. So maybe you hit one of those. IIRC most issues are fixed in
current and hopefully MFC-ed back.
Since FreeBSD 13 multipath routing is on by default but it is also
somewhat broken. Looking at your output I think this is actually a
multipath route. The super old OpenBGPD 5.2 version used by the FreeBSD
port has no concept of multipath routing (IIRC mpath support came later).
Maybe disabling multipath routing via sysctl can help.

Since OpenBGPD-portable 7.5 there is full FIB support for FreeBSD.
There will be an OpenBGP-portable 7.6 release in the next days which brings
a few important bug fixes. So best wait for that version to be out and open a
new ticket if this bug persists.

**Comment by janakktrivedi** [comment]
Thanks @cjeker  for the awesome information.  However it looks OpenBGDP 7.5 works in FreeBSD 12 only as can't see support for 13?

At the time of writing the portable version is known to build and work on:

 - OpenBSD
 - Alpine 3.15
 - Debian 9, 10
 - Fedora 34, 35, 36, 37
 - CentOS/RHEL/Rocky 7, 8, 9
 - Ubuntu 20.04 LTS
 - FreeBSD 12

**Comment by cjeker** [comment]
That list is not up to date.

I did implement the FIB support on FreeBSD 13 and I think it will also work with FreeBSD 12.
In general we try to support all actively maintained versions of the above list.

**Comment by janakktrivedi** [comment]
Thanks. I will try out.
