### ISSUE TITLE
TCP MD5 connection in FreeBSD should have per connection granularity

### ISSUE THREAD

**Issue by snallanc** [openbgpd-portable/openbgpd-portable#72]
openbgpd developers,
Happy new year 2024!

TCP MD5 connection in FreeBSD currently has per-host granularity which is evident from the fact that it uses a hard-coded SPI.
in pfkey_sa_add() function in pfkey-freebsd.c:

https://github.com/openbgpd-portable/openbgpd-portable/blob/master/src/bgpd/pfkey-freebsd.c#L524C1-L532C16
pfkey_sa_add(struct bgpd_addr *src, struct bgpd_addr *dst, uint8_t keylen,
    char *key, uint32_t *spi)
{
	/*
	 * From setkey(8):
	 * TCP-MD5 associations must use 0x1000 and therefore only
	 * have per-host granularity at this time.
	 */
	*spi = 0x1000;             <<<<
	if (pfkey_send(pfkey_fd, SADB_X_SATYPE_TCPSIGNATURE, SADB_ADD, 0,
	    src, dst, *spi, SADB_X_AALG_TCP_MD5, keylen, key,
	    SADB_EALG_NONE, 0, NULL, 0, 0) == -1)
		return (-1);
	if (pfkey_reply(pfkey_fd, NULL) == -1)
		return (-1);
	return (0);
}

It always uses an SPI value of 4096 or 0x1000. This works if there is just one TCP MD5 connection per host.
However if multiple TCP MD5 connections are configured on a host, subsequent connections after the first one would be assigned different SPI numbers by the FreeBSD kernel. However, bgpd would never know about the SPI assignments by the kernel.
Deleting a specific SA for a BGP connection in response to disabling MD5 on it could result in a failure since the SPI is not recorded anywhere in the userspace. The comment in pfkey_sa_add seems to indicate this is a known issue. If so, is there an ETA on when this could be fixed?

Thanks,
Sudarshan

**Comment by cjeker** [comment]
First of all OpenBGPD does not support multiple connections to the same host so this is not really an issue.
Why would you need this? Please explain?

Secondly this is not a OpenBGPD issue the problem is in FreeBSD. At least it seems the TCPMD5 implementation in FreeBSD still only supports host granularity (according to this comment: https://github.com/freebsd/freebsd-src/blob/8b144c015c9cce0bc99a7fbdc43f22f51a946d2c/sys/netipsec/xform_tcp.c#L338)

So the ETA to fix this right now is never (since this is a FreeBSD limitation).

**Comment by snallanc** [comment]
Thanks @cjeker for the response.
> Why would you need this? Please explain?
   Consider the scenario where a client device configured with an IPv4 and an IPv6 address has 2 BGP connections with a host(BGP router) running OpenBGPD. Without MD5, this scenario works fine for me. However, with MD5, while the security policies get pushed to SPD with unique SPIs relevant to each flow, we don't keep track of the SPIs anywhere for us to search and purge the correct SP entry when MD5 is disabled for a session where it was enabled befofe.

**Comment by snallanc** [comment]
Hi @cjeker did you get a chance to read my response above?

**Comment by cjeker** [comment]
I finally did some testing on a freebsd box. The code works fine. You can (re-)configure multiple TCP-MD5 sessions without and issue.
This includes an IPv4 and IPv6 session to the same host. Since it is impossible to configure and use two neighbors with the same IPs there should never be a conflict.

Also OpenBGPD handles the SPD all internally and does the required purges and updates.

**Comment by job** [comment]
@snallanc can you share your configuration if there still is a problem?

**Comment by snallanc** [comment]
Sorry about the delay. I too tested configuring multiple md5 bgp connections on the same host peered with multiple endpoints. Those all work fine. This can be closed.
